name: Run Python Script
run-name: DB Snapshot (${{ inputs.environment }})

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: choice
        default: 'dev'
        required: true
        options:
          - 'dev'
          - 'stg'
          - 'uat'
          - 'prd'
      confirm_prd:
        description: 'Type "CONFIRM_PRD" to allow PRD deployment'
        required: false
        default: 'NO'        
jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Prevent Accidental PRD Deployment
        if: ${{ inputs.environment == 'prd' && inputs.confirm_prd != 'CONFIRM_PRD' }}
        run: |
          echo "PRD deployment requires explicit confirmation."
          exit 1
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Run Python script
        run: python script2.py
