name: Run Python Script
run-name: DB Snapshot (${{ inputs.environment }})

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: choice
        default: 'dev'
        required: true
        options:
          - 'dev'
          - 'stg'
          - 'uat'
          - 'prd'
      confirm_prd:
        description: 'Type "CONFIRM_PRD" to allow PRD deployment'
        required: false
        default: 'NO'        
jobs:
  validate-access:
    runs-on: ubuntu-latest
    outputs:
      is_restricted: ${{ steps.check-user.outputs.is_restricted }}
    steps:
      - name: Check if User is in Restricted List
        id: check-user
        run: |
          RESTRICTED_USERS=("krishnakongara07" "dev-user2" "dev-user3")  # Add your dev group members here
          if [[ " ${RESTRICTED_USERS[@]} " =~ " ${GITHUB_ACTOR} " ]]; then
            echo "is_restricted=true" >> $GITHUB_ENV
            echo "User $GITHUB_ACTOR is restricted from deploying to PRD"
          else
            echo "is_restricted=false" >> $GITHUB_ENV
          fi

  deploy:
    runs-on: ubuntu-latest
    needs: validate-access
    if: ${{ !(inputs.environment == 'prd' && needs.validate-access.outputs.is_restricted == 'true') }}
    steps:
      - name: Prevent Unauthorized PRD Deployment
        if: ${{ inputs.environment == 'prd' && needs.validate-access.outputs.is_restricted == 'true' }}
        run: |
          echo "User $GITHUB_ACTOR is not allowed to deploy to PRD."
          exit 1

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Selected Environment
        run: echo "Deploying to ${{ inputs.environment }}"

      - name: Run Python script
        run: python script2.py
